use_frameworks!

target 'HanYangYangLib_Example' do
  pod 'HanYangYangLib', :path => '../'

  target 'HanYangYangLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
